services:
  eol-tool:
    container_name: eol-tool
    build: .
    image: salmutt/eol-tool:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - eol-cache:/root/.cache/eol-tool
    restart: unless-stopped
    environment:
      - EOL_TOOL_CACHE_DIR=/root/.cache/eol-tool
      - EOL_TOOL_DATA_DIR=/app/data
volumes:
  eol-cache:
